# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Biography
    url: /
    weight: 10
  - name: Publications
    url: /#papers
    weight: 11
  # - name: Projects
  #   url: projects/
  #   weight: 12
  # - name: Talks
  #   url: /#talks
  #   weight: 13
  # - name: News
  #   url: /#news
  #   weight: 13
  - name: Experience
    url: experience/
    weight: 14
  - name: CV
    url: uploads/resume.pdf
    weight: 15
  # - name: Teaching
  #   url: teaching/
  #   weight: 40
